Add test for floating point index in list.get()
uqbar-project/wollok-language pull request #103
Opened 2021-06-23 21:45 UTC by ezequielPereyra

Fix #87

2021-06-24 06:01 UTC, AngeliMatias commented
Dejo acá linkeado el [fix del issue 79](https://github.com/uqbar-project/wollok-ts/pull/85) que es con el que trabaja este test

2021-06-29 14:26 UTC, PalumboN requested changes
Esto hay que revisarlo con la lógica de Xtext, ahí puse algunos ejemplos representativos y cómo creo que funciona. Cualquier cosa le podemos preguntar a @fdodino

2021-06-29 14:26 UTC, PalumboN commented on test/sanity/collections/list.wtest
> +  }
Esto probablemente rompa en Xtext porque la lógica es la siguiente:
- Primero redondea a 5 decimales
- Después trunca la parte entera

Algunas pruebas:
```
>>> [1,2,3].get(0.1)
1
>>> [1,2,3].get(0.9)
1
>>> [1,2,3].get(0.99999)
1
>>> [1,2,3].get(0.999999)
2
>>> [1,2,3].get(0.111111111)
1
```

2021-07-07 18:07 UTC, PalumboN commented on test/sanity/collections/list.wtest
> +  }
Al final se cambió la implementación en xtext para que funcione como dice este test :+1:

2021-07-07 18:07 UTC, PalumboN approved these changes

2021-07-24 21:34 UTC, merged