Fixed issue 104
uqbar-project/wollok-language pull request #105
Opened 2021-06-24 00:49 UTC by AngeliMatias

Fix #104

2021-06-24 04:27 UTC, nscarcella commented
@AngeliMatias este PR solamente tiene tests, no? O faltó commitear algo?

2021-06-24 06:00 UTC, AngeliMatias commented
@nscarcella este PR va de la mano con el de wollok-ts que es [fix del issue 80](https://github.com/uqbar-project/wollok-ts/pull/86)

2021-06-29 14:37 UTC, PalumboN commented on test/sanity/game/game.wtest
> +  }
Esto creo que tiene los mismos problemas de redondeo que se mencionan en https://github.com/uqbar-project/wollok-language/pull/103#discussion_r660672141
Ver cómo avanza la discusión en https://github.com/uqbar-project/wollok-language/issues/87#issuecomment-870652608

2021-06-29 14:37 UTC, PalumboN commented on test/sanity/game/game.wtest
> +  }
Además pepita podría estar definida como object fuera del test, así no se repite.

2021-07-23 19:52 UTC, ezequielPereyra commented on test/sanity/game/game.wtest
> +  }
Al final quedamos en que usamos solo round, verdad?

2021-07-24 21:38 UTC, nscarcella approved these changes
Si ya están atendidos los comentarios de @PalumboN por mi está OK

2021-07-30 23:45 UTC, AngeliMatias commented
Pusimos la implementación de onSameCell() en wollok, agregamos un método round() para los números y para las positions. También agregamos tests para el funcionamiento de OnSameCell().

2021-07-31 00:42 UTC, nscarcella requested changes
Está muy bien. Agreguen algún test para el round de los números y estamos.

2021-07-31 06:14 UTC, nscarcella approved these changes

2021-08-02 20:34 UTC, PalumboN approved these changes
:+1:

2021-08-04 13:12 UTC, merged