Randomize list
uqbar-project/wollok-language pull request #127
Opened 2021-10-21 21:46 UTC by fabianfrangella

Implementa los siguientes metodos en List: 
randomize()
randomized()

Closes #91

2022-01-24 20:52 UTC, PalumboN requested changes
@fabianfrangella Muchas gracias por el aporte!! 🎉 

Ahí te dejé una sugerencia respecto a un comentario de doc que se puede commitear desde acá directamente.

Lo que sí estaría bueno es armar un test que valide esto, aunque sea superficialmente. Me imaginaba algo como:
```Wollok
const list = (1..100).asList()
const set = list.asSet()
const randomized = list.randomized()
assert.notEquals(list, randomized)
assert.equals(list.size(), randomized.size())
assert.equals(#{}, set.difference(randomized))
```
Y el análogo para el `randomize()`.

Eso debería pasar casi siempre y maso comprueba que haga algo de lo que se espera 🤔

2022-01-24 20:52 UTC, PalumboN commented on src/wollok/lang.wlk
> +  *     list.randomize() => list => [2, 1, 3]
```suggestion
  * Shuffles the order of the elements in the list.
  * This is a side effect operation.
  *
  * Examples:
  *     const list = [1, 2 ,3]
  *     list.randomize()     => list = [2, 1, 3]
```

2022-07-11 20:56 UTC, asanzo commented
Bueno, para cerrar esto veo que faltan los tests que propuso el @PalumboN .

2022-07-16 00:03 UTC, asanzo commented
@FerRomMu tuve una pequeña epifanía: Fui a ver al CLI cómo muestra los errores:
https://github.com/uqbar-project/wollok-ts-cli/blob/741b2dbc7aa60488f23e54b6fc7f7e9d9cf857a4/src/utils.ts#L53

Ese `node.sourceInfo()` hace la magia. Podríamos agregarlo a esta línea de ts, además de hacer el warn del problem, imprimir el sourceinfo:

https://github.com/uqbar-project/wollok-ts/blob/a33cc05c1e0ed0a8b97bb4956e90b40a335cc1b3/scripts/buildWRE.ts#L42

@nscarcella chequeame porfa que esta idea tenga sentido, para agregar info humana al output de buildWRE de TS.
Y ya que estás por acá, ¿Cómo se releasea este wollok-language? ¿Y cómo impacta un release de acá en otros proyectos, o más bien qué se espera? No encontramos cómo hacerlo en los readmes o en las wikis.

Gracias <3

2022-07-18 15:14 UTC, FerRomMu commented
> @FerRomMu tuve una pequeña epifanía: Fui a ver al CLI cómo muestra los errores: https://github.com/uqbar-project/wollok-ts-cli/blob/741b2dbc7aa60488f23e54b6fc7f7e9d9cf857a4/src/utils.ts#L53
> 
> Ese `node.sourceInfo()` hace la magia. Podríamos agregarlo a esta línea de ts, además de hacer el warn del problem, imprimir el sourceinfo:
> 
> https://github.com/uqbar-project/wollok-ts/blob/a33cc05c1e0ed0a8b97bb4956e90b40a335cc1b3/scripts/buildWRE.ts#L42
> 
> @nscarcella chequeame porfa que esta idea tenga sentido, para agregar info humana al output de buildWRE de TS. Y ya que estás por acá, ¿Cómo se releasea este wollok-language? ¿Y cómo impacta un release de acá en otros proyectos, o más bien qué se espera? No encontramos cómo hacerlo en los readmes o en las wikis.
> 
> Gracias <3

Ya ubique el problema. Es un tema de mergeo entre los commits mas nuevos del language y el fork. Específicamente el wollok-language actual tiene una linea en el mirror.wlk que es const property, que en el fork es const a secas y de ahí el warn. En mi local resolví el conflicto pero me saltan conflictos de divergencia en el remoto (no puedo simplemente mergear a mi fork/master el uqbar/master como normalmente lo hago con dos ramas distintas de un mismo remoto). Pero si ignoramos el tema conflictos de remotos, una vez mergeado todo ya no tira la warn (porque se agrega dicha linea de código) y pasa todos los test de sanity.

2022-07-18 18:07 UTC, merged

2022-07-18 19:01 UTC, nscarcella commented
Para "relesear" lang solamente se crea un tag acá en GitHub con la nueva
versión semántica en el formato de los otros. Relesear lang no impacta a
nadie, porque cada implementación apunta a una versión fija de lang.

El vie, 15 jul 2022 a la(s) 21:03, asanzo ***@***.***)
escribió:

> @FerRomMu <https://github.com/FerRomMu> tuve una pequeña epifanía: Fui a
> ver al CLI cómo muestra los errores:
>
> https://github.com/uqbar-project/wollok-ts-cli/blob/741b2dbc7aa60488f23e54b6fc7f7e9d9cf857a4/src/utils.ts#L53
>
> Ese node.sourceInfo() hace la magia. Podríamos agregarlo a esta línea de
> ts, además de hacer el warn del problem, imprimir el sourceinfo:
>
>
> https://github.com/uqbar-project/wollok-ts/blob/a33cc05c1e0ed0a8b97bb4956e90b40a335cc1b3/scripts/buildWRE.ts#L42
>
> @nscarcella <https://github.com/nscarcella> chequeame porfa que esta idea
> tenga sentido, para agregar info humana al output de buildWRE de TS.
> Y ya que estás por acá, ¿Cómo se releasea este wollok-language? ¿Y cómo
> impacta un release de acá en otros proyectos, o más bien qué se espera? No
> encontramos cómo hacerlo en los readmes o en las wikis.
>
> Gracias <3
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/uqbar-project/wollok-language/pull/127#issuecomment-1186030910>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFPE2YDGTK3DC32EXUGRTTVUH34LANCNFSM5GPEGEHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>