Feature removing constructors
uqbar-project/wollok-language pull request #83
Opened 2020-11-23 05:08 UTC by fdodino

Issues resueltos

- #63

2020-12-12 14:02 UTC, PalumboN approved these changes
Para mí está todo piola. Me gustaría que @nscarcella @npasserini @lspigariol @asanzo vean este PR para asegurar que estamos todos de acuerdo con lo que charlamos en las reuniones.

2020-12-16 03:01 UTC, fdodino commented on test/sanity/language/initialization/namedParametersBadDefinitions.wtest
> +  // }
sí, deberíamos crear un issue para ésto. El validador de xtext lo chequea, pero si lo ejecutás directo de la consola te quedan referencias sin inicializar.

2020-12-16 03:01 UTC, fdodino commented on test/sanity/customObjects/namedObjects/singletonsCustom.wtest
> +object o2 inherits B { }
ese código quedó rancio. Ya lo ajusté y ahora lo subo.

2020-12-16 03:02 UTC, fdodino commented on test/sanity/customObjects/namedObjects/singletonsCustom.wtest
> +object o2 inherits B { }
También eliminé la palabra constructor, había ejemplos que quedaron con constructores incluso, no solo con la descripción de los escenarios.

2020-12-16 03:04 UTC, fdodino commented
Bueno,  @nscarcella @npasserini @lspigariol @asanzo , un poco prefiero esperar a que cerremos este tema para poder avanzar con lo que sigue del Roadmap (son cambios muy disruptivos para encararlos en paralelo), y otro poco puedo empezar a trabajar en otros asuntos. Vuelvo en febrero, ahí es donde tiro el timeout.

2020-12-17 21:11 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +	}
El PR hermano de Xext se encarga de eso: 

![image](https://user-images.githubusercontent.com/4549002/102544229-4233e700-4093-11eb-8e20-c7574b29a6fc.png)

Por eso el mensaje arriba de todo es:

> Ojo que hay que mergearlo con uqbar-project/wollok#1978

2020-12-24 01:42 UTC, nscarcella requested changes

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/defaultConstructorCall.wtest
> +  test "default instantiation inherited from object class should work" {
Este test no lo entendí muy bien. Se está testeando que no explote por no pisar el initialize? No parece haber nada redefinido en la jerarquía.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/inheritedConstructorCall.wtest
> +  assert.that(true)
Si hay que poner un assert para que no chille, capaz mejor asertar que el arma es la esperada?

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +		a = 1
Esto habíamos dicho que no se podía hacer. El initialize iba a ser un método más y, por lo tanto, no puede pisar un const.

Quote de lo que menciona @npasserini en el issue (https://github.com/uqbar-project/wollok-language/issues/62#issuecomment-691743511):
> No es necesario tener reglas especiales en el initialize [...] Atributos que no queremos que se puedan pasar por parámetro en la construcción => vamos a definir otro mecanismo para eso.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +	var property b
Este caso sí es válido, el initialize puede pisar un var. El llamado a super() es optativo y queda a criterio del desarrollador (como en cualquier otro método). Estaría bueno agregar un  test sin super para dejarlo claro.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +	var property b
Ahí vi que la clase C tiene uno.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +	const c = new C()
Siguiendo con el hilo de lo que decía arriba, como `a` es un const sin default, y no va a poder ser pisado en el initialize, para instanciar `C` hay que pasarle `a`.
Es decir, las constantes que no tengan un valor por default tienen que pasarse al instanciar sí o sí.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +		assert.equals(null, c.a())
Esto sería correcto si a fuera un var. Como es un const es imposible.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesComplexCase.wtest
> +		a = 1
Asignación inválida. Para pisar `a` tiene que ser var.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesComplexCase.wtest
> +    a = 5
idem arriba

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesLazy.wtest
> +
Yo agregaría el caso:
```wollok
  test "overriding default initialization: variable -> value" {
    assert.equals(2, new C().b())
  }
```

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesLazy.wtest
> +
Bah, mirando de nuevo capaz está comprendido indirectamente por un de abajo, pero bueno. Mejor que sobre

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/namedParametersBadDefinitions.wtest
> +  // this test is covered by validation but not by interpreter
No entendí. Quiere decir que no podemos tener el test?

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/namedParametersBadDefinitions.wtest
> +  //   assert.throwsException { new Ave(edad = 22) }
Esto, si no entiendo mal, no es correcto. `energía`es un var, con lo cual, si no lo inicializas debería quedar "sin inicializar" (o sea, `null`, al menos de momento). Que conste que yo prefería un mundo donde me obligabas a pasarlo, pero esa discusión la perdí.

Estaría bueno agregar el mismo test pero con un `const`, el cual sería cierto que te obligaría a pasarlo.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/language/initialization/namedParametersBadDefinitions.wtest
> +  //   assert.throwsException { new Ave(edad = 22) }
Amplío un poco por las dudas:
La idea era que vos podrías querer inicializar un var directamente en el initialize y, para que el initialize pueda ser un método sin reglas especiales (porque para detectar esto consistentemente necesitás un chequeador de efecto), hay que aceptar la posibilidad de que un `var` que no me pasas en construcción y no tiene default puede quedar sin inicializar.

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/testing/describe/initializeMethod.wtest
>      uno = 1
Aca tampoco

2020-12-24 01:42 UTC, nscarcella commented on test/sanity/testing/describe/initializeMethod.wtest
>      uno = 1
No se puede

2020-12-24 01:47 UTC, nscarcella commented
@fdodino ahí dejé comentarios. Si querés decime que doc tomamos de referencia y cuando tenga un rato hago el volcado de lo que recuerdo de las discusiones.

Perdón por no revisar los PR de xtext, pero me exceden.

2020-12-24 02:54 UTC, fdodino commented
@nscarcella , agarrá el doc que está deprecado y actualizalo que me parece es el que tiene la definición más completa

2020-12-24 03:00 UTC, fdodino commented on test/sanity/language/initialization/defaultConstructorCall.wtest
> +  test "default instantiation inherited from object class should work" {
exacto. No hay parámetros nombrados, ni initialize, ni nada. Son parte de las clases de equivalencia.

2020-12-24 03:00 UTC, fdodino commented on test/sanity/language/initialization/inheritedConstructorCall.wtest
> +  assert.that(true)
ok.

2020-12-24 03:09 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +		a = 1
bueno, _plot twist_, acabo de probar ésto:

```wollok
/**
  * Scenario: a hierarchy of classes, one of them uses initialize from superclass 
	* and the other simply overrides it
  */
class A {
	const property a
	
	method initialize2() {
		a = 1
	}
}

describe "1" {
	
	test "no se puede inicializar una constante en un initialize" {
		const a = new A(a = 0)
		a.initialize2()
		assert.equals(1, a.a())
	}
}
```

Si bien el validador chilla, si ejecuto el test funciona. Así que hay algo para cambiar desde tiempos inmemoriales para Wollok.

2020-12-24 03:22 UTC, nscarcella commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +		a = 1
No, bueno. Imagino que no hay mucha razón para restringir la evaluación mientras el validador no lo deje pasar. Supongo que, al final del día, un atributo es un atributo. El tema es que en la consola también se valide... En los prototipos que hicimos en TS corremos el validador en el repl también, no sé si eso se podrá en xtext

2020-12-24 12:04 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +		a = 1
la consola ejecuta el validador:
![image](https://user-images.githubusercontent.com/4549002/103087161-54e37a00-45c5-11eb-8168-613152d25838.png)

igualmente, si la referencia la definiste como constante, el intérprete debe tirar error, 1) por consistencia, 2) si no toda esta especificación no se puede probar.

2020-12-24 12:05 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +	var property b
ok, resuelvo esta conversación para saber que no tengo que hacer nada

2020-12-24 12:28 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +	const c = new C()
Ok, ahí cambié de const a var y agregué nuevos tests validando que al intentar hacer `new` de objetos que tienen en el initialize una asignación eso haga que el intérprete tire error

2020-12-24 12:28 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesBasic.wtest
> +		assert.equals(null, c.a())
Parte del cambio que hice aplica para todo este archivo

2020-12-24 12:32 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesComplexCase.wtest
> +		a = 1
Cambié de `const` a `var`

2020-12-24 12:32 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesComplexCase.wtest
> +    a = 5
done

2020-12-24 12:33 UTC, fdodino commented on test/sanity/language/initialization/initializeMethodOnClassesLazy.wtest
> +
Agregué ese test.

2020-12-24 12:34 UTC, fdodino commented on test/sanity/language/initialization/namedParametersBadDefinitions.wtest
> +  // this test is covered by validation but not by interpreter
Dado que es un cambio fuerte en el intérprete me gustaría atacarlo en otro PR.

2020-12-24 12:37 UTC, fdodino commented on test/sanity/language/initialization/namedParametersBadDefinitions.wtest
> +  //   assert.throwsException { new Ave(edad = 22) }
Yo creo que hay una validación fácil que puede hacer el intérprete: si una vez instanciado un objeto, donde recorrimos sus parámetros nombrados, asignamos valores por defecto, ejecutamos el initialize, queda alguna referencia apuntando a `null`, podemos eventualmente tirar un error. Esto lo podemos hacer en runtime, más allá de que a futuro sí podríamos tener un sistema que chequee el efecto y tener esa validación en el momento previo a la ejecución.

Yo no estoy tan seguro de que hayas perdido esa batalla, a mí me gustaría plantearlo a ver qué dicen.

Pero claramente no en este PR.

2020-12-24 12:38 UTC, fdodino commented on test/sanity/testing/describe/initializeMethod.wtest
>      uno = 1
Ya lo cambié, quedó un poco retorcido pero al menos lo estamos validando:

```wollok
describe "const references cannot be initially assigned in a test initialization" {
  const uno

  method initialize() {
    assert.throwsException { => uno = 1 }
  }

  test "uno es uno" {
    assert.equals(null, uno)
  }
}

describe "const references cannot be additionally assigned in a test initialization" {
  const uno = 1

  method initialize() {
    assert.throwsException { => uno = 1 }
  }

  test "uno es uno" {
    assert.equals(1, uno)
  }
}
```

2020-12-24 12:38 UTC, fdodino commented on test/sanity/testing/describe/initializeMethod.wtest
>      uno = 1
done

2020-12-24 12:40 UTC, fdodino commented
@nscarcella , el doc en cuestión para evitar confusiones sería [éste](https://docs.google.com/document/d/1DnRnRKnO3IDQya3NZJqj-U-6ICrAhgUhaqpuZfGjRFk/edit)

Estoy subiendo los cambios que hice, más tarde subo los de Xtext.

2021-01-05 02:18 UTC, nscarcella commented
@fdodino actualicé el doc. Fijate el comentario que dejé [acá](https://github.com/uqbar-project/wollok-language/issues/62#issuecomment-754251719). Abrazo.

2021-01-15 15:29 UTC, fdodino commented
@nscarcella fijate si te cierra ahora el PR para aprobarlo, revisé el doc y corregí o mejoré el código en base a los ejemplos. Lo que más me importa es poder liberar el PR de Xtext, este PR puede mergearse al feature branch release-3.0.0.

Mi idea es que en marzo liberemos el nuevo release para poder testearlo en UNQ, UNSAM y UNAHur.

2021-02-13 20:33 UTC, nscarcella commented on test/sanity/language/initialization/lazyInitializationComplex.wtest
> +/**
Mismo

2021-02-14 13:00 UTC, fdodino commented on test/sanity/language/initialization/assignmentInInitialize.wtest
> +		assert.throwsException { => new D() }
La definición de la clase D tira error de validación:

![image](https://user-images.githubusercontent.com/4549002/107877407-08246d00-6eab-11eb-9b74-df84a970b7a5.png)

Por otra parte, para poder correr los tests de wollok-language necesitás apagar las validaciones porque si no un montón de tests fallan mucho antes que pueda levantar el runtime. El script que corremos es

```bash
wollok test -dontValidate
```

Este test solo valida que el runtime falle también, porque actualmente en Wollok Xtext vos podés ejecutar los tests aun cuando el validador tire errores, y queremos que haya consistencia (hubo casos donde los tests dan verde).

2021-02-14 13:01 UTC, fdodino commented on test/sanity/language/initialization/assignmentInInitialize.wtest
> +		assert.throwsException { => new E() }
Sí, el mismo caso que te comentaba arriba.

2021-02-14 13:03 UTC, fdodino commented on test/sanity/language/initialization/defaultConstructorCall.wtest
> +/**
dale

2021-02-14 13:03 UTC, fdodino commented on test/sanity/language/initialization/inheritedConstructorCall.wtest
> +/**
lo cambié a `chainedInstantiation`

2021-02-14 13:04 UTC, fdodino commented on test/sanity/basics/pairs/pairs.wtest
> +  test "new pair named parameter" {
bueno, ahí cambié la descripción de Pair y Arrow

2021-02-14 13:06 UTC, fdodino commented on test/sanity/language/initialization/namedParametersBadDefinitions.wtest
> +  //   assert.throwsException { new Ave(edad = 22) }
acordate que eso va para otro PR

2021-02-14 13:07 UTC, fdodino commented on test/sanity/language/initialization/lazyInitializationAssigningParameters.wtest
> +  * Scenario: a class with lazy definitions, changed by named parameters
oook, sale cambio a cyclic definitions

2021-02-14 13:12 UTC, fdodino commented on test/sanity/language/initialization/lazyInitializationAssigningParameters.wtest
> +  * Scenario: a class with lazy definitions, changed by named parameters
mejor a dependent definitions

2021-02-14 20:49 UTC, merged