Cambio en las expectativas de los sanities de lazyness
uqbar-project/wollok-language pull request #90
Opened 2021-01-07 02:39 UTC by nscarcella

Buenas,

Mergeando el refactor monstruo de TS me encontré unos tests que creo que no están bien.

Hasta ahora, cuando hablamos de lazyness en los campos siempre lo hicimos para las declaraciones (objects, classes y mixines), pero estos tests sugieren lazyness en **expresiones**. El problema que hay ahí es que es muy osado plantear lazyness automática en los parámetros del `new` o, lo que es básicamente lo mismo, en el llamado al super-constructor de los singletons (no así los de las clases, porque esas todavía hay que instanciarlas), porque una expresión asume un orden de ejecución. Bah, hasta Scala te obliga a poner un coso especial cuando querés que un parámetro sea lazy, me parece fuerte. Yo creo que ese es un terreno más bien aspero que amerita discutirlo por separado.

En definitiva lo que hice fue:
- Eliminar los dos tests que requerían expresiones (no declaraciones) con parametros lazy.
- Agregar un test más para garantizar que las declaraciones de objects inline no sean lazy tampoco.

Por otro lado, probé el test de la referencia cruzada en Wollok-xtext y tirá stack overflow, con lo cual no hay manera de que estos tests estén pasando así que imagino que los estamos skipeando (eso o hay que revisar a ver qué onda).

Si no están de acuerdo chiflen.

2021-01-08 17:22 UTC, PalumboN commented
@nscarcella  Los tests de referencia cruzadas en el new de una const global se implementó en xtext acá: https://github.com/uqbar-project/wollok/pull/1970 (en base a este issue: https://github.com/uqbar-project/wollok/issues/1957). Creo que si apuntas tu Wollok a la versión dev en vez de la stable te debería funcionar.

A mi me parecía bien esa definición, porque tanto los objects como las constantes globales son lazy.

2021-01-08 19:54 UTC, nscarcella commented
Uhm... Si es así necesito una definición más en detalle de cómo se tiene que comportar y en qué casos.

Si ese test pasa, entonces quiere decir que la expresión que se pasa como parámetro al new se está postergando. Eso seguro no querés que pase siempre. Si se hace solamente para las instanciaciones en constantes globales entiendo que puede no ser un problema, pero me da que es medio inconsistente.

O sea, este código funcionaría:

```wollok
class A { const b }
class B { const a }

const a = new A(b = b)
const b = new B(a = a)
```
pero este no:

```wollok
class A { const b }
class B { const a }

test "esto no es global" {
  const a = new A(b = b)
  const b = new B(a = a)
}
```

Habría que ver si adentro de un describe funciona o no, pero ahora que estamos eliminando los fixtures y va a haber más initialize poder hacerlo a nivel global solamente podría ser confuso. O sea, lo lindo de las otras lazyness que hablamos es que son transparentes, apenas más que un hoisting. Pero esto medio que te cambia la semántica de la expresión dependiendo en dónde la escribas.

Ojo, no digo que tiremos para atrás lo que se hizo, pero capaz podríamos, de momento, no establecerlo como un feature del lenguaje y discutir alguna forma de poder crear estas referencias cruzadas en todos lados.

Si soy al único que le hace ruido, OK, dejemos los tests como están, pero tengo preguntas:

- Dónde se aplica esta lazyness para los parametros de instanciación? variables de packages? Variables de describes? Variables de métodos? Variables de Clases/Mixines/Objects? - Variables de Bloques, Ifs y otras expresiones?
- Se hace lazy cualquier parámetro que se pase o sólo referencias?
- No hay ningún caso donde una expresión de `new` a nivel global necesite mantener el orden de evaluación? Entiendo que aceptamos que la respuesta es "no" porque le apuntamos a que las definiciones globales sean "puras", pero bueno, por eso pregunto si esto aplica sólo a nivel global.
- Qué pasa con las definiciones de objetos anónimos (globales y no globales) en todos estos casos?

2021-01-08 19:55 UTC, nscarcella commented
Arrobo a @fdodino y @npasserini a ver qué piensan.

2021-01-11 00:43 UTC, fdodino commented
Yo tengo que ver el ejemplo que no funciona, mi intención es ver hasta dónde puedo hacerme el gil y permitir que funcionen los parámetros lazy. Dame unos buenos días porque estoy de vacaciones.

2021-01-17 13:26 UTC, fdodino commented
Acabo de probar este ejemplo:

```wollok
class A { const b }
class B { const a }

describe "ufa" {

  test "esto no es global" {
    const a = new A(b = b)
    const b = new B(a = a)
  }

}
```

y funciona. 

Lo que hoy hacemos en Wollok Xtext es que los named parameters que le pasás a una instancia de Wollok Object al crearla con `new` se instancian siempre eager, a menos de que...:

```wollok
	def initializeObject(WollokObject wollokObject, EList<WInitializer> namedParameters) {
		namedParameters.forEach([ namedParameter |
			val value = 
				if (namedParameter.initialValue.shouldBeLazilyInitialized)
					new LazyWollokObject(interpreter, wollokObject.behavior, [ | namedParameter.initialValue.eval ])
				else
					namedParameter.initialValue.eval

			wollokObject.setReference(namedParameter.initializer.name, value)			
		])
	}
```

...la referencia que le pasamos sea global:

```wollok
	def static dispatch boolean shouldBeLazilyInitialized(EObject e) { false }
	def static dispatch boolean shouldBeLazilyInitialized(WVariableReference v) { v.ref.global }	
```

Esa heurística permite diferir todas las instanciaciones que dependen de `const`, `object` y cosas que a futuro marquemos como globales. Por eso el ejemplo que armaste no funciona, porque las variables que estás definiendo dentro del tests son locales.

A mí esa heurística no me hace ruido, es decir, no me molesta como docente contar que para poder cruzar referencias éstas tienen que ser globales. De todas maneras si hay un fuerte consenso en diferir todas las ejecuciones hasta su primer momento de uso, bueno, podemos armar una propuesta: a mí particularmente me tienta volver el cambio que hice para atrás y tener como Kotlin un modfiicador para forzar estos casos

```wollok
  test "esto no es global" {
    const lazy a = new A(b = b)
    const lazy b = new B(a = a)
  }
```

Pero bueno... esto amerita una discusión.
```

2021-01-17 13:28 UTC, fdodino requested changes
Por el momento preefiero quedarme con el cambio actual y no eliminar el test que está basado en el issue  https://github.com/uqbar-project/wollok#1957

2021-01-17 16:42 UTC, nscarcella commented
@fdodino gracias por el contexto.

No me queda claro cuando una referencia se considera global. En ese cacho de código yo hubiera pensado que en `new A(b = b)` la referencia `b` apunta a `const b = new B(a = a)`, que estando declarada dentro de un test yo no la hubiera considerado global.

> a mí particularmente me tienta volver el cambio que hice para atrás y tener como Kotlin un modfiicador para forzar estos casos

Para mi esto es indispensable para las expresiones pero estoy de acuerdo que amerita discusión.

Voy a cerrar este PR y mandar un mail para gatillar la charla de la laziness.

2021-01-17 22:50 UTC, fdodino commented
@nscarcella, solo para aclarar el punto de qué es considerable global:

```xtend
	/** A variable is global if its declaration (i.e. its eContainer) is direct child of a WFile element */
	def static dispatch boolean isGlobal(WVariableDeclaration it) {
		eContainer instanceof WFile
	}
	def static dispatch boolean isGlobal(WVariable it) {
		declaration.isGlobal
	}
	def static dispatch boolean isGlobal(WNamedObject it) { true }
	def static dispatch boolean isGlobal(WParameter it) { false }
	def static dispatch boolean isGlobal(WCatch it) { false }
```

- los named objects (singletons) son globales
- las variables que están definidas en un file son globales (las `const`)

Cualquier otro caso: parámetros, variables de un describe, variables locales de un método o test, variables de instancia de un object/class no son globales.

Es decir, lo que es global lo podés acceder directamente como referencia en la consola.

2021-01-18 23:19 UTC, nscarcella commented
@fdodino Uhm... Pero Fer, si no entiendo mal entonces el código que ponés más arriba no debería funcionar:

```wollok
class A { const b }
class B { const a }

describe "ufa" {

  test "esto no es global" {
    const a = new A(b = b)
    const b = new B(a = a)
  }

}
```
`a` y `b` son constantes definidas en el contexto de un test, con lo cual no deberían considerarse globales si no entendí mal. Cuando haces `new A(b = b)` esperaría que el `initialValue` del parámetro sea la referencia a la constante `b`, que al no ser global debería evaluarse en el lugar y, o bien entrar en un loop o bien valer `null` o algo así.

No estoy seguro si agarré algo mal, pero no lo estoy entendiendo.

2021-01-19 00:14 UTC, fdodino commented
Sí, tenés razón, porque falta entender una cosa sola más: los tests se evalúan en el contexto actual del intérprete. No hay WollokObject, por lo tanto todo este juego del lazyness no ocurre. Podría eventualmente forzar a que cada test construya un WollokObject e intuyo que eso lo arreglaría. También podríamos simplemente cambiar la sintaxis y obligar a que todo test esté encerrado en un describe, mantener ambas variantes me parece que no suma mucho.

2021-02-14 03:38 UTC, nscarcella commented
@fdodino @PalumboN Reabro esto en base a lo que hablamos en la reunión de roadmap. La propuesta es mover esos tests a xtext y hacer una propuesta de lazyness posta posta más adelante.

2021-02-14 18:18 UTC, fdodino commented
Bueno @nscarcella , lo que hice por el momento fue mover estos dos tests de `cyclicReferences.wtest`:

```wollok
test "cyclic references for instance named params" {
  assert.that(unEntrenador.estaContento())
  assert.that(unEquipo.bienEntrenado())
}

test "cyclic references for named objects with inherits named params" {
  assert.that(elEntrenador.estaContento())
  assert.that(elEquipo.bienEntrenado())
} 
```

a Wollok Xtext, en particular el super-mega-archi-recontra PR de eliminar constructores. Acá me parece que te falta eliminar el segundo test de wollok-language y estaríamos, pero en Wollok Xtext es más fácil tener a ambos conviviendo y cuando quieras lo eliminamos de language.

2021-02-14 18:19 UTC, fdodino commented
perdón cuando dije mover me refería a **crear**, no toqué nada en Wollok Language para que este PR siga su curso.

2021-02-14 20:54 UTC, fdodino commented
@nscarcella : el PR de eliminar constructores lo mergeé contra el feature branch release-3.0.0, me gustaría que éste y todo lo que conforme el release 3.0 vaya a ese mismo lugar también. Si no hablemos y pongámonos de acuerdo para que después mergear no sea muy doloroso.

2021-02-17 03:37 UTC, nscarcella commented
@fdodino Sí, tenés razón. Traté de hacerlo acá en github pero se trula un poco con el merge. Mañana trato de rebasearlo bien.

2021-02-22 17:38 UTC, PalumboN commented
Ok! Pero por qué mover los tests a Xtext hasta que tengamos una propuesta mejor? Por qué no dejarlos acá así ya estamos en sintonía, y cuando tengamos algo mejor no cambiar ambas implementaciones?
Bah, no sé bien lo que hablaron el otro día, lo comento porque me parece mejor el tener alguna referencia al estado actual del arte vs "perderla" entre los tests de Xtext :P
Igual los sigo con lo que hayan decidido!!

2021-02-22 18:23 UTC, nscarcella commented
@PalumboN El tema es que TS no tiene implementados estos manejos para casos particulares y eso hace que no pasen los tests. Implementar estos manejos es bastante contramano y preferiría no sumarle complejidad al modelo para algo que queremos deprecar.

2021-02-22 21:21 UTC, PalumboN commented
@nscarcella Ahh okok, pensé que estaba implementado en TS también. Perfecto.

2021-02-26 02:32 UTC, nscarcella commented
@fdodino ahí rebasié y apunté el PR a `release-3.0.0`. Si te parece bien mergeamos así puedo relesear TS

2021-02-26 02:42 UTC, fdodino approved these changes

2021-02-26 02:44 UTC, fdodino commented
Ok, solo me da un poquito de cosa que haya nombres `o` y `x`. Pero dale para adelante.

2021-02-26 03:13 UTC, merged