Assert enhancements
uqbar-project/wollok-language pull request #94
Opened 2021-03-07 17:40 UTC by fdodino

2021-03-14 00:18 UTC, nscarcella requested changes

2021-03-14 00:18 UTC, nscarcella commented on src/wollok/lib.wlk
> +      throw new AssertionException(message = "Block " + block + " should not have failed")
Capaz sería interesante no perder e. Se puede poner como causa de la otra excepción o agregar la clase y el texto al mensaje?

2021-03-16 00:50 UTC, fdodino commented on src/wollok/lib.wlk
> +      throw new AssertionException(message = "Block " + block + " should not have failed")
Sí, tenés razón.

```wollok
  method doesNotThrowException(block) {
    try {
      block.apply()
    } catch e {
      throw new AssertionException(message = "Block " + block + " should not have failed with <" + e.message() + ">", cause = e)
    }
  }
```

@nscarcella , te va?

2021-03-16 02:14 UTC, fdodino commented on src/wollok/lib.wlk
> +      throw new AssertionException(message = "Block " + block + " should not have failed")
![image](https://user-images.githubusercontent.com/4549002/111245903-2681a380-85e4-11eb-8172-0e4c7fb87e00.png)

@nscarcella

2021-03-16 06:27 UTC, nscarcella commented on src/wollok/lib.wlk
> +      throw new AssertionException(message = "Block " + block + " should not have failed")
(Y)

2021-03-16 06:27 UTC, nscarcella approved these changes

2021-03-16 21:09 UTC, merged